### PR TITLE
Add antitrust policy

### PR DESCRIPTION
**Pull request by tkuhrt**

### CODE REVIEW

**Comment by swcurran** [comment]
There should be the image of the policy included somewhere (not sure where). I grabbed the one from the TAC meeting agenda today and it is very hard to read — the white text on a dark background.  Suggest including the image in this PR (since that is what will be used in most places) and create a clearer image.

**Comment by swcurran** [comment]
Yeah — the black one white text is not great — especially when shrunk to fit nicely beside the code of conduct. The old Hyperledger version was easier to see and read.

**Comment by tkuhrt** [comment]
@swcurran : Can you see if the black text on white background attached here is any better?

**Comment by swcurran** [comment]
Way better — thanks!  Here is an example of agenda pages with the [new image](https://wiki.hyperledger.org/display/ARIES/2024-09-26+Aries+Working+Group+Call) and the [old image](https://wiki.hyperledger.org/display/ARIES/2024-10-01+Aries+Cloud+Agent+-+Python+Users+Group+Community+Meeting).  The new one you created is WAY better. 

I’ll update the page that is in the old format — so check it out soon :-) .

**Review by swcurran — APPROVED** [review]

**Review by ryjones — APPROVED** [review]

**Pull request merged**
